version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: markdown-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - markdown-network
    environment:
      - MONGO_INITDB_DATABASE=markdown-app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: markdown-server
    restart: always
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/markdown-app
      - DOMAIN=${DOMAIN:-kickshare.fun}
      - CLIENT_URL=https://${DOMAIN:-kickshare.fun}
    networks:
      - markdown-network  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - DOMAIN=${DOMAIN:-kickshare.fun}
    container_name: markdown-client
    restart: always
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=https://${DOMAIN:-kickshare.fun}/api
      - REACT_APP_DOMAIN=${DOMAIN:-kickshare.fun}
    networks:
      - markdown-network

  nginx:
    image: nginx:alpine
    container_name: markdown-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./client/build:/usr/share/nginx/html
    depends_on:
      - client
      - server
    networks:
      - markdown-network

networks:
  markdown-network:
    driver: bridge

volumes:
  mongodb_data:
